let Myimg1 = document.getElementById("img1")
let Myimg2 = document.getElementById("img2")
let Myimg3 = document.getElementById("img3")
let Myimg4 = document.getElementById("img4")
let Myimg5 = document.getElementById("img5")
let Myimg6 = document.getElementById("img6")
let Myimg7 = document.getElementById("img7")
let Myimg8 = document.getElementById("img8")
let Myimg9 = document.getElementById("img9")
let Modal123 = document.getElementById("modalimg")

Myimg1.addEventListener('click', () => {Modal123.innerHTML='<img src="https://picsum.photos/id/120/760/760">'})
Myimg2.addEventListener('click', () => {Modal123.innerHTML='<img src="https://picsum.photos/id/250/760/760">'})
Myimg3.addEventListener('click', () => {Modal123.innerHTML='<img src="https://picsum.photos/id/350/760/760">'})
Myimg4.addEventListener('click', () => {Modal123.innerHTML='<img src="https://picsum.photos/id/450/760/760">'})
Myimg5.addEventListener('click', () => {Modal123.innerHTML='<img src="https://picsum.photos/id/550/760/760">'})
Myimg6.addEventListener('click', () => {Modal123.innerHTML='<img src="https://picsum.photos/id/650/760/760">'})
Myimg7.addEventListener('click', () => {Modal123.innerHTML='<img src="https://picsum.photos/id/760/760/760">'})
Myimg8.addEventListener('click', () => {Modal123.innerHTML='<img src="https://picsum.photos/id/860/760/760">'})
Myimg9.addEventListener('click', () => {Modal123.innerHTML='<img src="https://picsum.photos/id/950/760/760">'})